
version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo Hello

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo World!
  
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: 'echo an env variable part of our project'
          command: |
            echo $BRYSON_ENV_VAR

workflows:
  welcome:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
  test-env-vars:
    jobs:
      - build
  

