
version: 2.1

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1 # simulating error exit code
      - run:
          name: on error
          command: echo "Its an error"
          when: on_fail
workflows:
  my_workflow:
    jobs:
      - my_job